---
title: "Commuting Services"
always_allow_html: true
output: 
  html_document:
    toc: true
    code_folding: hide
    toc_float: true
---
```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(lubridate)
library(gganimate)
library(zoo)
library(tis)
library(scales)
library(plotly)
```
```{r input citibike membership data, include=FALSE}
membership_df = 
  read_csv("ridership.csv") %>%
  mutate(date = factor(date, ordered = TRUE, levels = c("01/2019", "02/2019", "03/2019", "04/2019",
                                                         "05/2019", "06/2019", "07/2019", "08/2019",
                                                         "09/2019", "10/2019", "11/2019", "12/2019",
                                                         "01/2020", "02/2020", "03/2020", "04/2020",
                                                         "05/2020", "06/2020", "07/2020", "08/2020",
                                                         "09/2020", "10/2020", "11/2020", "12/2020",
                                                         "01/2021", "02/2021", "03/2021", "04/2021",
                                                         "05/2021", "06/2021", "07/2021", "08/2021",
                                                         "09/2021", "10/2021"))) %>%
  rename(ct_annual_members = annual_members) %>%
  rename(ct_single_trip_passes = single_trip_passes) %>%
  rename(ct_single_day_passes = single_day_passes) %>%
  rename(ct_three_day_passes = three_day_passes) %>%
  rename(ct_total_annual_members = total_annual_members) %>%
  mutate(date = as.yearmon(date, "%m/%Y")) %>%
  mutate(date = as.jul(date)) %>%
  mutate(date = as.Date(date)) %>%
  pivot_longer(
    cols = starts_with("ct"),
    names_to = "measure",
    values_to = "count"
  ) 


measures_of_interest =
  membership_df %>%
  filter(measure %in% c("ct_annual_members","ct_single_day_passes","ct_single_trip_passes"))
```

```{r animated graph, message=FALSE}
measures_of_interest %>%
  ggplot(aes(x = date, y = count)) +
  geom_line(aes(group = measure, color = measure)) +
  geom_point(aes(group = seq_along(date), color = measure)) +
  transition_reveal(date) +
  scale_x_date(breaks = "4 months", labels = date_format("%b-%Y")) +
  scale_colour_discrete(name = "Membership Type",
                        breaks = c("ct_annual_members", "ct_single_day_passes",
                                   "ct_single_trip_passes"),
                        labels = c("Annual Passes Renewed or Purchased",
                                   "Single-Day Passes Purchased",
                                   "Single-Trip Passes Purchased")) +
  labs(x = "Date", y = "Count") +
  ggtitle("CitiBike Memberships Purchased by Month in NYC and New Jersey City") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  guides(color = guide_legend(nrow = 2, byrow = TRUE)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

```{r, input manhattan rides data, message=FALSE}
manhattan_rides_df <- read_csv("manhattan_rides.csv")

manhattan_rides_df <-
  manhattan_rides_df %>% 
  mutate(
    day_of_week = factor(day_of_week, ordered = T, 
                         levels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")), 
    year = factor(year), 
    age_group = factor(age_group, ordered = T,
                       levels = c("18-25","26-35", "36-45", "46-55", "56-65", "66-85")), 
    gender = type.convert(gender, as.is = F))

```

```{r, percent change dataset, message=FALSE, warning=F}
citi_pc_change =
  manhattan_rides_df %>%
  mutate(date = format(stoptime, format = "%m-%d-%Y")) %>%
  group_by(stop_date, year) %>%
  summarize(daily_rides = n()) %>%
  ungroup() %>%
  group_by(stop_date) %>%
  arrange(year, .by_group = T) %>%
  mutate(percent_change = (daily_rides/lag(daily_rides) - 1) * 100) %>%
  filter(year == 2020) %>%
  select(date = stop_date, percent_change) %>%
  mutate(transit_system = "citi_bike",
     	date = paste0("2020-", date),
     	date = as.Date(date, "%Y-%m-%d"))
```

```{r, copied from subway_rides RMD, message=FALSE, warning=F}
#Ridership data for 2019/2020 Manhattan
turnstiles_2019_m = read_csv("2019-turnstile.csv") %>% 
  filter(borough == "M") %>% 
  mutate(gtfs_latitude = as.numeric(gtfs_latitude),
         gtfs_longitude = as.numeric(gtfs_longitude))
  
  
turnstiles_2020_m = read_csv("2020-turnstile.csv") %>% 
    filter(borough == "M") %>% 
    mutate(gtfs_latitude = as.numeric(gtfs_latitude),
         gtfs_longitude = as.numeric(gtfs_longitude))

turnstiles_19_20_m = rbind(turnstiles_2019_m, turnstiles_2020_m)

#Ridership data 3/1/2020 - today
ridership_covid_changes = read_csv("covid-ridership.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date(date, "%m/%d/%Y")) %>% 
  rename(buses_ter = buses_total_estimated_ridership) %>% 
  rename(lirr_ter = lirr_total_estimated_ridership) %>% 
  rename(metro_north_ter = metro_north_total_estimated_ridership) %>% 
  rename(subways_ter = subways_total_estimated_ridership) %>% 
  rename(subways_pc = subways_percent_change_from_pre_pandemic_equivalent_day) %>% 
  rename(metro_north_pc = metro_north_percent_change_from_2019_monthly_weekday_saturday_sunday_average) %>% 
  rename(lirr_pc = lirr_percent_change_from_2019_monthly_weekday_saturday_sunday_average) %>% 
  rename(buses_pc = buses_percent_change_from_pre_pandemic_equivalent_day) %>% 
  rename(bridges_and_tunnels_pc = bridges_and_tunnels_percent_change_from_pre_pandemic_equivalent_day) %>% 
  rename(access_a_ride_ter = access_a_ride_total_scheduled_trips) %>% 
  rename(access_a_ride_pc = access_a_ride_percent_change_from_pre_pandemic_equivalent_day)


ridership_covid_changes_2020 = ridership_covid_changes %>% 
  filter(date <= as.Date('2020-12-31'))

ridership_covid_pc_tidy = 
  ridership_covid_changes_2020 %>% 
  
  select(date, access_a_ride_pc, bridges_and_tunnels_pc, buses_pc, lirr_pc, metro_north_pc, subways_pc) %>% 
  
  pivot_longer(
    c(access_a_ride_pc:subways_pc), 
    names_to = "transit_system",
    values_to = "percent_change"
  ) %>% 
  
   mutate(transit_system = gsub("_pc", "", transit_system),
          percent_change = gsub("%", "", percent_change),
          percent_change = as.numeric(percent_change))
```

```{r, Join datasets, message=FALSE, warning=F}
ridership_pc_change = 
  bind_rows(ridership_covid_pc_tidy, citi_pc_change)
```

```{r, plot with everything, message=FALSE, warning=F}
# Using plotly 
ridership_pc_change %>% 
  ungroup() %>% 
  drop_na() %>% 
  filter(date >= as.Date('2020-03-01')) %>% 
  plot_ly(
    x = ~date, 
    y = ~percent_change, 
    color = ~transit_system,
    type = "scatter",
    mode = "lines") %>% 
  layout(
    title = "Ridership Transit System Percent Change Following COVID",
    xaxis = list(title = "Date"),
    yaxis = list(title = "Percent Change")
  )
```