---
title: "Travel Patterns"
always_allow_html: true
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(leaflet)
library(dplyr)
library(plotly)
library(ggplot2)
library(ggthemes)
library(gganimate)
library(maps)
library(rgdal)
library(sf)
library(magick)

library(viridis)

knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE
)

theme_set(theme_minimal())

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r, read in manhattan rides data}
manhattan_rides_df <- read_csv("manhattan_rides.csv")

manhattan_rides_df <-
  manhattan_rides_df %>% 
  mutate(
    day_of_week = factor(day_of_week, ordered = T, 
                         levels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")), 
    year = factor(year), 
    age_group = factor(age_group, ordered = T,
                       levels = c("18-25","26-35", "36-45", "46-55", "56-65", "66-85"))
  )
```

```{r, Rides by day of week}
manhattan_rides_df %>% 
  group_by(day_of_week, year) %>% 
  summarize(obs = n()) %>% 
  ggplot(aes(x = day_of_week, y = obs, group = year, color = year)) +
  geom_point() + 
  geom_line() +
  labs(x = "Day of the Week", y = "Number of Rides", col = "Year") +
  ggtitle("Citibike Rides by Day of the Week") +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r, read in hubs and hospital data}
hubs_df = 
  read_csv("hubs.csv") %>% 
  drop_na()

hospitals_df = 
  read_csv("hospitals.csv") %>% 
  drop_na()
```

```{r, rides in 2019 vs 2020 by month}
nyc = 
  as_tibble(
    map_data("state")
  ) %>% 
  filter(subregion == "manhattan")

bikes_month_2019 = manhattan_rides_df %>% 
  filter(year == "2019") %>% 
  mutate(
    month = format(starttime, format = "%m"),
    month = as.numeric(month)
  ) %>% 
  group_by(month, end_station_longitude, end_station_latitude) %>% 
  summarise(n_rides = n())

bikes_month_2020 = manhattan_rides_df %>%
  filter(year == "2020") %>% 
  mutate(
    month = format(starttime, format = "%m"),
    month = as.numeric(month)
  ) %>%
  group_by(month, end_station_longitude, end_station_latitude) %>% 
  summarise(n_rides = n())

map_month_2019 = 
  ggplot() +
  geom_polygon(data = nyc, aes(x = long, y = lat, group = group), fill = "grey", alpha = 0.5) +
  geom_point(data = bikes_month_2019, aes(x = end_station_longitude, y = end_station_latitude, size = 0.25, color = n_rides), alpha = 0.5) +
  scale_size(range = c(1,8), name = "Rides") +
  geom_point(data = hospitals_df, aes(x = Long, y = Lat), color = "red") + 
  geom_point(data = hubs_df, aes(x = Long, y = Lat), color = "green") +
  transition_time(month) +
  labs(
    title = "2019 Month: {frame_time}", 
    color = "Rides",
    x = "Longitude",
    y = "Latitude") +
  enter_grow() +
  exit_shrink() +
  ease_aes("sine-in-out") +
  coord_cartesian(ylim = c(40.68, 40.85), xlim = c(-74.02, -73.925))


map_month_2020 = 
  ggplot() +
  geom_polygon(data = nyc, aes(x = long, y = lat, group = group), fill = "grey", alpha = 0.5) +
  geom_point(data = bikes_month_2020, aes(x = end_station_longitude, y = end_station_latitude, size = 0.25, color = n_rides), alpha = 0.5) +
  scale_size(range = c(1,8), name = "Rides") +
  geom_point(data = hospitals_df, aes(x = Long, y = Lat), color = "red") + 
  geom_point(data = hubs_df, aes(x = Long, y = Lat), color = "green") +
  transition_time(month) +
  labs(
    title = "2020 Month: {frame_time}", 
    color = "Rides",
    x = "Longitude",
    y = "Latitude") +
  theme(legend.position = "none") +
  enter_grow() +
  exit_shrink() +
  ease_aes("sine-in-out") +
  coord_cartesian(ylim = c(40.68, 40.85), xlim = c(-74.02, -73.925))

#combining both animations using magick package
a_month_gif = animate(map_month_2019, duration = 12, fps = 1, width = 400, height = 400)
b_month_gif = animate(map_month_2020, duration = 12, fps = 1, width = 400, height = 400)

a_month_mgif = image_read(a_month_gif)
b_month_mgif = image_read(b_month_gif)

new_month_gif = image_append(c(a_month_mgif[1], b_month_mgif[1]))
for (i in 2:12) {
  combined_month = image_append(c(a_month_mgif[i], b_month_mgif[i]))
  new_month_gif = c(new_month_gif, combined_month)
}

new_month_gif
```

In mid-2020, Citi Bike expanded stops into northern Manhattan, driving the expansion of the bubble graph area seen in late-2020. 

```{r, zoomed daily map}
bikes_2019 = manhattan_rides_df %>% 
  filter(year == "2019") %>% 
    group_by(stop_date, end_station_longitude, end_station_latitude) %>% 
  summarise(n_rides = n()) %>% 
  mutate(
    date = paste0("2019-", stop_date),
         date = as.Date(date, "%Y-%m-%d"))

bikes_2020 = manhattan_rides_df %>%
  filter(year == "2020") %>% 
    group_by(stop_date, end_station_longitude, end_station_latitude) %>% 
  summarise(n_rides = n()) %>% 
  mutate(
    date = paste0("2020-", stop_date),
         date = as.Date(date, "%Y-%m-%d"))

timeline_2019 = 
  bikes_2019 %>% 
  filter(date >= as.Date("2019-02-16"), date <= as.Date("2019-06-30"))

timeline_2020 = 
  bikes_2020 %>% 
  filter(date >= as.Date("2020-02-16"), date <= as.Date("2020-06-30"))

daily_map_2019 = 
  ggplot() +
  geom_polygon(data = nyc, aes(x = long, y = lat, group = group), fill = "grey", alpha = 0.5) +
  geom_point(data = timeline_2019, aes(x = end_station_longitude, y = end_station_latitude, size = 0.25, color = n_rides), alpha = 0.5) +
  geom_point(data = hospitals_df, aes(x = Long, y = Lat), color = "red") + 
  geom_point(data = hubs_df, aes(x = Long, y = Lat), color = "green") +
  transition_time(date) +
  labs(
    title = "Date: {frame_time}", 
    color = "Rides",
    x = "Longitude",
    y = "Latitude") +
  scale_fill_continuous(breaks = c(2.5, 5.0, 7.5, 10.0, 12.5)) +
  enter_grow() +
  exit_shrink() +
  ease_aes("sine-in-out") +
  coord_cartesian(ylim = c(40.725, 40.775), xlim = c(-74.0125, -73.925))

daily_map_2020 = 
  ggplot() +
  geom_polygon(data = nyc, aes(x = long, y = lat, group = group), fill = "grey", alpha = 0.5) +
  geom_point(data = timeline_2020, aes(x = end_station_longitude, y = end_station_latitude, size = 0.25, color = n_rides), alpha = 0.5) +
scale_fill_continuous(limits = c(0,12.5), breaks = c(0, 2.5, 5.0, 7.5, 10.0, 12.5)) +
  geom_point(data = hospitals_df, aes(x = Long, y = Lat), color = "red") + 
  geom_point(data = hubs_df, aes(x = Long, y = Lat), color = "green") +
  transition_time(date) +
  labs(
    title = "Date: {frame_time}", 
    color = "Rides",
    x = "Longitude",
    y = "Latitude"
    ) +
  theme(legend.position = "none") +
  enter_grow() +
  exit_shrink() +
  ease_aes("sine-in-out") +
  coord_cartesian(ylim = c(40.725, 40.775), xlim = c(-74.0125, -73.925))

#combining both animations using magick package
a_daily_gif = animate(daily_map_2019, duration = 30, fps = 2, width = 400, height = 400)
b_daily_gif = animate(daily_map_2020, duration = 30, fps = 2, width = 400, height = 400)

#combining both animations using magick package
a_daily_gif = animate(daily_map_2019, duration = 30, fps = 2, width = 400, height = 400)
b_daily_gif = animate(daily_map_2020, duration = 30, fps = 2, width = 400, height = 400)

a_daily_mgif = image_read(a_daily_gif)
b_daily_mgif = image_read(b_daily_gif)

new_daily_gif = image_append(c(a_daily_mgif[1], b_daily_mgif[1]))
for (i in 2:60) {
  combined_daily = image_append(c(a_daily_mgif[i], b_daily_mgif[i]))
  new_daily_gif = c(new_daily_gif, combined_daily)
}

new_daily_gif
```

